name: evolve_fitness_app
description: "A Collaborative Habit Tracker"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  auto_size_text: ^3.0.0
  supabase_flutter: ^2.10.0
  fluttertoast: ^8.2.12
  flutter_floating_bottom_bar: ^1.3.0
  intl: ^0.20.2
  provider: ^6.0.0
  flutter_riverpod: ^2.3.6
  shared_preferences: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true


